# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

#############
#   Notes   #
#############

# This config assumes you have a Nerd Font installed and enabled in your terminal.
# I use 'FiraCode Nerd Font Mono', but you should be able to use any Nerd Font you like.

################
#   Settings   #
################

# Inserts a blank line between shell prompts
add_newline = true

# Maximum time it may take to produce the prompt
command_timeout = 3000

########################
#   Webber's colours   #
########################

# Bright pink: (bg:#e6b6f2 fg:#452152)
# Middle pink, bright text: (bg:#5e386a fg:#f9d8ff)
# Middle pink, faded text: (bg:#5e386a fg:#f9d8ff)
# Dark pink, regular text: (bg:#514254 fg:#f2dcf3)
# Dark pink, highlighted: (bg:#514254 fg:#e6b6f2)

###############
### PROMPTS ###
###############

# Left prompt
format = """
[](bg:transparent fg:#89b4fa)\
$os\
$username\
[](fg:#89b4fa bg:#1e1e2e)\
$directory\
${custom.pregit}\
$git_branch\
$git_state\
$git_metrics\
$git_status\
${custom.postgit}\
${custom.nogit}\
$package\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$bun\
$nim\
$rust\
$scala\
$docker_context\
$character\
"""

# Right prompt (Time & Memory)
right_format = """
[](bg:transparent fg:#1e1e2e)\
$time\
$memory_usage\
[](fg:#1e1e2e bg:transparent)\
\
"""

########################
### SPECIAL SECTIONS ###
########################

# Exit code indicator (The arrow at the end)
[character]
success_symbol = '[](bg:#1e1e2e fg:#89b4fa)[󱇫](bg:#89b4fa fg:#1e1e2e)[](fg:#89b4fa bg:transparent)'
error_symbol = '[](bg:#1e1e2e fg:#ffb4ab)[󱇫](bg:#ffb4ab fg:#690005)[](fg:#ffb4ab bg:transparent)'
format = '$symbol '

# Username (The first pill)
[username]
show_always = true
style_user = "bg:#89b4fa fg:#1e1e2e"
style_root = "bg:#89b4fa fg:#1e1e2e"
format = '[ $user]($style)'

# OS Symbol (The Icon)
[os]
style = "bg:#89b4fa fg:#1e1e2e"
format = '[$symbol]($style)'
disabled = false

# The current directory (The middle darker pill)
[directory]
style = "bg:#1e1e2e fg:#89b4fa"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = "…/"

[time]
disabled = false
time_format = "%R"
style = "bg:#1e1e2e fg:#89b4fa"
format = '[$time]($style)'

#######################
#   Version control   #
#######################


[git_branch]
symbol = ""
style = "bg:#514254 fg:#f2dcf3"
format = '[](fg:#5e386a bg:#514254)[ $symbol](bg:#514254 fg:#e6b6f2)[ $branch ]($style)'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[🍒 PICKING](bg:#514254 fg:bold red)'
rebase = '[ REBASING](bg:#514254 fg:bold green)'
merge = '[ MERGING](bg:#514254 fg:bold yellow)'
bisect = '[🔍 BISECTING](bg:#514254 fg:bold blue)'
am = '[AM](bg:#514254 fg:bold green)'
am_or_rebase = '[AM/REBASE](bg:#514254 fg:bold green)'
revert = '[󰕍 REVERTING](bg:#514254 fg:bold red)'

[git_metrics]
added_style = "bg:#514254 fg:#f5b7b3"
deleted_style = "bg:#514254 fg:#ffb4ab"
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'
disabled = false

[git_status]
style = "bg:#514254 fg:#e6b6f2"
conflicted = '=' # This branch has merge conflicts.
ahead = ''
behind = ''
diverged = '󱡷'
up_to_date = ''
untracked = '?'
stashed = ''
modified = ''
staged = ''
renamed = '»'
deleted = '✘'
format = '([($all_status )($ahead_behind )]($style))[](bg:#514254 fg:#5e386a)'

[fossil_branch]
symbol = ""

[hg_branch]
symbol = ""

[pijul_channel]
symbol = ""

############################
#   Contexts (canonical)   #
############################

[nodejs]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[bun]
symbol = "󰅟"
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[docker_context]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ (context) ]($style)'

[package]
format = '($style)[> $symbol$version ]($style)'
symbol = '📦 '
version_format = 'v${raw}'
style = 'bold 208 bg:#5e386a'
display_private = false
disabled = true
################
#   Contexts   #
################

[aws]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[c]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[conda]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[dart]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[elixir]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[elm]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[golang]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[gradle]
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[haskell]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[haxe]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[java]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[julia]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[kotlin]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[lua]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[ocaml]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[perl]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[php]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[python]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[rlang]
symbol = "󰟔"
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[ruby]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[scala]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[swift]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

[zig]
symbol = ""
style = "bg:#5e386a fg:#f9d8ff"
format = '[$symbol](bg:#5e386a fg:#e6b6f2)[ ($version) ]($style)'

#############
#   Other   #
#############

[nix_shell]
symbol = ""

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
