###############
### SOURCES ###
###############

### Do not change
source = ~/.local/share/dotfiles/default/hypr/conf/autostart.conf
source = ~/.local/share/dotfiles/default/hypr/conf/nvidia-env.conf
source = ~/.local/share/dotfiles/default/hypr/conf/laptop-keybindings.conf
source = ~/.local/share/dotfiles/default/hypr/conf/looknfeel.conf
source = ~/.local/share/dotfiles/default/hypr/conf/windowrules.conf
source = ~/.local/share/dotfiles/default/hypr/conf/layerrules.conf
source = ~/.local/share/dotfiles/current/theme/hyprland.conf

### Can change these, create more files and import here if needed
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/input.conf
# source = ~/.config/hypr/my_custom_file.conf

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = elephant &
exec-once = /usr/local/bin/walker --gapplication-service
exec-once = waybar &
exec-once = hyprpaper &
exec-once = rfkill unblock all
exec-once = nmcli radio wifi on
exec-once = ~/.config/hypr/fix-portals.sh
input {
    # Touchpad settings
    touchpad {
        natural_scroll = true
        tap-to-click = true
        drag_lock = true
        clickfinger_behavior = true
    }
    kb_layout = us
    kb_options = caps:escape_shifted_capslock

}

bind = , XF86PowerOff, exec, wlogout
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_SINK@ toggle
bindl = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_SINK@ 5%-
bindl = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_SINK@ 5%+
bindl = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_SOURCE@ toggle

bindl = , XF86MonBrightnessDown, exec, brightnessctl set 5%-
bindl = , XF86MonBrightnessUp, exec, brightnessctl set 5%+

misc {
    vfr = true  # <--- This turns the feature on
}

# Option 1: Full Screen Instant (No popup, just saves)
bind = , Print, exec, grim ~/Pictures/Screenshot_$(date +'%s').png

# Option 2: Select Area (Shift + Print)
bind = SHIFT, Print, exec, grim -g "$(slurp)" ~/Pictures/Screenshot_$(date +'%s').png

# Force the system to ignore NVIDIA for standard desktop apps
env = __EGL_VENDOR_LIBRARY_FILENAMES,/usr/share/glvnd/egl_vendor.d/50_mesa.json
env = __GLX_VENDOR_LIBRARY_NAME,mesa
