###############
### SOURCES ###
###############

### Do not change
source = ~/.local/share/dotfiles/default/hypr/conf/autostart.conf
source = ~/.local/share/dotfiles/default/hypr/conf/nvidia-env.conf
source = ~/.local/share/dotfiles/default/hypr/conf/laptop-keybindings.conf
source = ~/.local/share/dotfiles/default/hypr/conf/looknfeel.conf
source = ~/.local/share/dotfiles/default/hypr/conf/windowrules.conf
source = ~/.local/share/dotfiles/default/hypr/conf/layerrules.conf
#source = ~/.local/share/dotfiles/current/theme/hyprland.conf
#
### Can change these, create more files and import here if needed
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/input.conf
# source = ~/.config/hypr/my_custom_file.conf

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = elephant &
exec-once = /usr/local/bin/walker --gapplication-service
exec-once = waybar &
exec-once = hyprpaper &
exec-once = rfkill unblock all
exec-once = nmcli radio wifi on
exec-once = ~/.config/hypr/fix-portals.sh
exec-once = ~/.config/hypr/scripts/power_profile.sh
exec-once = ~/.config/hypr/scripts/init_notifications.sh

# Force apps to use Wayland immediately (skips X11 startup time)
env = GDK_BACKEND,wayland,x11
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland

# Firefox Speedup
env = MOZ_ENABLE_WAYLAND,1

input {
    # Touchpad settings
    touchpad {
        natural_scroll = true
        tap-to-click = true
        drag_lock = true
        clickfinger_behavior = true
    }
    kb_layout = us
    kb_options = caps:escape_shifted_capslock

}

bind = , XF86PowerOff, exec, wlogout

# Volume with OSD Notification
bindl = , XF86AudioRaiseVolume, exec, ~/.config/hypr/scripts/volume.sh up
bindl = , XF86AudioLowerVolume, exec, ~/.config/hypr/scripts/volume.sh down
bindl = , XF86AudioMute, exec, ~/.config/hypr/scripts/volume.sh mute
bindl = , XF86Launch6, exec, ~/.config/hypr/scripts/mic_toggle.sh

# Brightness with OSD Notification
bindl = , XF86MonBrightnessUp, exec, ~/.config/hypr/scripts/brightness.sh up
bindl = , XF86MonBrightnessDown, exec, ~/.config/hypr/scripts/brightness.sh down

# Airplane Mode
bindl = , XF86RFKill, exec, ~/.config/hypr/scripts/airplane.sh

# Touchpad
# Both keys trigger the same "Flip Switch" script
bindl = , XF86TouchpadOff, exec, ~/.config/hypr/scripts/touchpad.sh
bindl = , XF86TouchpadOn, exec, ~/.config/hypr/scripts/touchpad.sh
misc {
    vfr = true  # <--- This turns the feature on
    vrr = 1
}

# Option 1: Full Screen Instant (No popup, just saves)
bind = , Print, exec, grim ~/Pictures/Screenshot_$(date +'%s').png

# Option 2: Select Area (Shift + Print)
bind = SHIFT, Print, exec, grim -g "$(slurp)" ~/Pictures/Screenshot_$(date +'%s').png

# Force NVIDIA to handle Hyprland (Smoothness)
env = WLR_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0

env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

