general {
    # 1. The Lock Command
    # We use 'pidof' to check if it's already running. 
    lock_cmd = pidof hyprlock || hyprlock

    # 2. The Critical Fix
    # We force the lock AND wait 3 seconds to let the GPU render the lock screen 
    # before the system creates the suspend snapshot.
    before_sleep_cmd = loginctl lock-session && sleep 5

    # 3. Wake Up Actions
    # Turn screen ON and restore brightness immediately
    after_sleep_cmd = hyprctl dispatch dpms on && brightnessctl -r
}

# --- Idle Stages ---

# Stage 1: Dim the screen after 2.5 minutes (Save battery while reading)
listener {
    timeout = 150
    on-timeout = grep -q 1 /sys/class/power_supply/AC*/online || brightnessctl -s set 10
    on-resume = brightnessctl -r                 # Restore previous brightness
}

# Stage 2: Turn off the screen after 5 minutes (The biggest saver)
listener {
    timeout = 300
    on-timeout = grep -q 1 /sys/class/power_supply/AC*/online || hyprctl dispatch dpms off       # Screen purely off
    on-resume = hyprctl dispatch dpms on         # Screen on
}

# Stage 3: Lock the session after 10 minutes (Security)
listener {
    timeout = 600
    on-timeout = grep -q 1 /sys/class/power_supply/AC*/online || loginctl lock-session
}

# Stage 4: Suspend the PC after 20 minutes (Stop all battery drain)
listener {
    timeout = 1200
    on-timeout = grep -q 1 /sys/class/power_supply/AC*/online || systemctl suspend
}
